### ISSUE TITLE
known_count not always updated properly for letters with > 1 usage

### ISSUE THREAD

**Issue by mjskay** [coolbutuseless/wordle#1]
Thanks for the great package! It's been very fun using it to try to hack together a wordle solver.

I found a minor bug in `WordleHelper` that crops up very rarely (only on words with duplicate letters and only in some sequences of guesses). I think it is caused by a difference between how `WordleGame` reports duplicates (it only reports the first instance as `"yellow"`, which I *think* is how Wordle does it?) and how `WordleHelper` counts filters duplicates (it seems to assume if there are two letters in the word and two letters in the guess both will be either `"green"` or `"yellow"`). Example:

```r
library(wordle)

helper = WordleHelper$new(nchar = 5)
"essay" %in% helper$words
#> [1] TRUE

game = WordleGame$new(words = wordle_dict, target_word = "essay")

# try out a word with two "s"s in it in the wrong positions
# I believe the report from WordleGame here is consistent with what Wordle does
response = game$try("sease")
#> [38;5;232m[48;5;226m s [48;5;226m e [48;5;226m a [48;5;249m s [48;5;249m e [39m[49m
response
#> [1] "yellow" "yellow" "yellow" "grey"   "grey"

# update the helper's state...
helper$update("sease", response)
# ... and "essay" is no longer in the word list
"essay" %in% helper$words
#> [1] FALSE

# the problem appears to be that known_count thinks
# there is only one "s" in the word, causing "essay" to
# be filtered out
helper$known_count
#> s e 
#> 1 1
```

<sup>Created on 2022-01-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Anyway, thanks again for this! The API has been very pleasant to use.

**Comment by coolbutuseless** [comment]
Looks like a bug in `WordleGame`
 Attempting 'sease' with 'essay' as the target word should return:

`yellow, yellow, yellow, yellow, grey`

**Comment by coolbutuseless** [comment]
@mjskay  - i also added a 'quiet' argument to WordleGame$try() which might makes things easier/cleaner when getting the computer to play against itself.

**Comment by mjskay** [comment]
beautiful, thanks for both!
