### ISSUE TITLE
Missing yellow for second instance of letter

### ISSUE THREAD

**Issue by steveharoz** [coolbutuseless/wordle#2]
If the target is `terse`, and `steer` is guessed, it should have all yellow letters.

But the second `e` isn't yellow.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/2257540/148915294-b1346338-c99b-4c8c-aa1f-c630615fbea6.png">

**Comment by coolbutuseless** [comment]
Are you on latest version v0.1.6?

**Comment by steveharoz** [comment]
Oops. I didn't realize there was a recent update. That fixed it. Thanks!
